import { Noto_Sans, Roboto } from "next/font/google";
import "./globals.css";

const notaSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-nota-sans",
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Bookstore",
  description: "Generated by Bookstore",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
      </head>
      <body className={(notaSans.className, roboto.className)}>{children}</body>
    </html>
  );
}
